src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $nb_books = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Book::class)]
    private Collection $book;

    public function __construct()
    {
        $this->book = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getNbBooks(): ?int
    {
        return $this->nb_books;
    }

    public function setNbBooks(int $nb_books): static
    {
        $this->nb_books = $nb_books;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBook(): Collection
    {
        return $this->book;
    }

    public function addBook(Book $book): static
    {
        if (!$this->book->contains($book)) {
            $this->book->add($book);
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->book->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->username;
    }
}

src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use App\Repository\AuthorRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AuthorController extends AbstractController
{
    #[Route('/author', name: 'app_author')]
    public function index(): Response
    {
        return $this->render('author/index.html.twig', [
            'controller_name' => 'AuthorController',
        ]);
    }
    #[Route('/listA', name: 'list_author')]
    public function listAuthor(AuthorRepository $rep):Response{
        $result=$rep->findAll();
        return $this->render("author/authorList.html.twig",
        ['author'=>$result
    ]);
    }
    #[Route('/add', name: 'add_author')]
    public function add(ManagerRegistry $mr):Response{
        $a=new Author();
        $a->setUsername("hama");
        $a->setEmail("hama@gmail.com");
        $em=$mr->getManager();
        $em->persist($a);
        $em->flush();
        return $this->redirectToRoute("list_author");
    }

    #[Route('/addF', name: 'addF_author')]
    public function addF(ManagerRegistry $mr,Request $req):Response{
        $a=new Author();
        $form=$this->createForm(AuthorType::class,$a);
        $form->handleRequest($req);
        if($form->isSubmitted()){
            $em=$mr->getManager();
            $em->persist($a);
            $em->flush();
            return $this->redirectToRoute("list_author");
        }
        return $this->render("author/form.html.twig",
        ['formA'=>$form->createView(),
    ]);
    }
    #[Route('/update/{id}', name: 'update' ,methods:['GET','POST'])]
    public function updatee(EntityManagerInterface $em ,ManagerRegistry $doctrine,$id,Request $req,AuthorRepository $repo):Response
    {
        $c=$repo->find($id);//recuperation
        $form=$this->createForm(AuthorType::class,$c); 
        $form->handleRequest($req); 
        if($form->isSubmitted())
        {
        $em=$doctrine->getManager();
        $em->flush();

         
        return $this->redirectToRoute('list_author');
        }
        $formView=$form->createView(); 

        return $this->render('author/form.html.twig',[
        'formA'=>$formView
        ]);

    }

    #[Route('/delete/{id}', name: 'delete')]
    public function delete(AuthorRepository $repo,$id,ManagerRegistry $mr): Response
    {
        $s=$repo->find($id);
        $em=$mr->getManager();
        $em->remove($s);
        $em->flush();
        return $this->redirectToRoute('list_author');

    }
    #[Route('/qb1',name:'listAuthorbyemail')]
    public function qb(AuthorRepository $repo){
        $result=$repo->listAuthorByEmail();
     //dd($result);
     return $this->render("author/authorList.html.twig",
        ['author'=>$result
    ]);

    }


}

templates/author/authorList.html.twig
<h1>List des auteurs </h1>
<table border="1">
    <tr>
        <th>Username </th>
        <th>Email </th>
        <th>Number of books</th>
        <th>Actions </th>
        
        
    </tr>
    <tr>
       <tr>{% for a in author%}</tr>
       <td>{{ a.username}} </td>
       <td>{{ a.email}} </td>
       <td>{{ a.nbBooks}}</td>
       <td>
       <a href="{{path('update',{'id': a.id})}}">edit</a>
       <a href="{{path('delete',{'id': a.id})}}">delete</a>
       </td>
        {% endfor %}
    </tr>
</table>

templates/author/form.html.twig
{{form_start(formA)}}
{{ form_widget(formA) }}
<button type="submit">save</button>
{{ form_end(formA) }}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AuthorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/hp/ilyes/src/Controller/AuthorController.php'|file_link(0) }}">src/Controller/AuthorController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/hp/ilyes/templates/author/index.html.twig'|file_link(0) }}">templates/author/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/author/list.html.twig
{% if authors is defined and authors|length > 0 %}
   {% for author in authors %}
      <td>{{ author.id }}</td>
      <td><img src="{{ author.picture }}" alt="{{ author.username }}" width="100"></td>
      <td>{{ author.username|upper }}</td>
      <td>{{ author.email }}</td>
      <td>{{ author.nb_books }}</td>
       <td><a href="{{ path('author_details', {'id': author.id}) }}">Détails</a></td>

   {% endfor %}  
    <p>Nombre d'auteurs : {{ authors|length }}</p>
    {%set s=0%}
   {% for i in authors %}
     {% set s=s+i.nb_books %}
   {% endfor %}
      
<p>Nombre de livre:{{s}}  </p> 
{% else %}  
<p>Aucun auteur n'est disponible.</p>
{% endif %}

templates/author/show.html.twig
<h1> {{ n }}! ✅</h1>